version: org.riotkit.rkd/0.3
imports:
    - rkd.standardlib.python
    - rkd.standardlib.docker
    - rkt_ciutils.boatci
    - rkt_ciutils.docker

env_files:
    - env/build-settings.env

tasks:
    :build-all-versions:
        description: Build all versions of Taiga
        arguments:
            "--commit-msg":
                required: True
        steps: |
            rkd :boat-ci:process --commit-message="${ARG_COMMIT_MSG}"

    :build:snapshot:
        description: Build a single version of Taiga image
        arguments:
            "--backend-version":
                required: True
            "--frontend-version":
                required: True
        steps: >
            rkd :boat-ci:specific-release \
            --app-version="${ARG_BACKEND_VERSION}" \
            --docker-build-opts="--build-arg FRONTEND_VERSION=${ARG_FRONTEND_VERSION}" \
            --docker-version="${ARG_BACKEND_VERSION}-SNAPSHOT" \
            --no-push

    :generate-readme:
        description: Before commiting, please regenerate the README.md from template
        steps: rkd :docker:generate-readme -f ./Dockerfile -rt ./README.md.j2 --target-path ./README.md
